apiVersion: v1
kind: Service
metadata:
  name: chatbot-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: chatbot
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 3000

